In [1]:
import pandas as pd
import pickle

In [2]:
import time
import pandas as pd
from sqlalchemy import create_engine
import psycopg2

In [31]:
sellers = pd.read_pickle("PROGRAMACAO/teste/sellers.pkl")
sellers.head(3)

,id,nickname,registration_date,country_id,user_type,points,permalink,status,city,state,level_id,power_seller_status,transactions_completed
0,124201,AI1999,1999-12-23,BR,normal,27838,http://perfil.mercadolivre.com.br/AI1999,active,São Paulo,SP,5_green,gold,4134
1,125058,MAISFPSBR,1999-12-27,BR,normal,150,http://perfil.mercadolivre.com.br/MAISFPSBR,active,Santana de Parnaíba,SP,5_green,platinum,1321
2,349856,CONSTRUMAR-LC,2000-06-15,BR,normal,2223,http://perfil.mercadolivre.com.br/CONSTRUMAR-LC,active,Marapoama,SP,5_green,platinum,11730

In [36]:
sellers['registration_date'] = sellers['registration_date'].dt.date

In [39]:
sellers.head(3)

,id,nickname,registration_date,country_id,user_type,points,permalink,status,city,state,level_id,power_seller_status,transactions_completed
0,124201,AI1999,1999-12-23,BR,normal,27838,http://perfil.mercadolivre.com.br/AI1999,active,São Paulo,SP,5_green,gold,4134
1,125058,MAISFPSBR,1999-12-27,BR,normal,150,http://perfil.mercadolivre.com.br/MAISFPSBR,active,Santana de Parnaíba,SP,5_green,platinum,1321
2,349856,CONSTRUMAR-LC,2000-06-15,BR,normal,2223,http://perfil.mercadolivre.com.br/CONSTRUMAR-LC,active,Marapoama,SP,5_green,platinum,11730

In [43]:
sellers = sellers[['id', 'nickname', 'registration_date', 'user_type',
       'points', 'permalink', 'status', 'city', 'state', 'level_id',
       'power_seller_status', 'transactions_completed']]

In [45]:
sellers.columns

Index(['id', 'nickname', 'registration_date', 'user_type', 'points',
       'permalink', 'status', 'city', 'state', 'level_id',
       'power_seller_status', 'transactions_completed'],
      dtype='object')

In [27]:
(sellers.power_seller_status.str.len().sort_values())

0       4.0
1138    4.0
2924    4.0
1135    4.0
1134    4.0
       ...
3812    NaN
4074    NaN
4546    NaN
4826    NaN
4999    NaN
Name: power_seller_status, Length: 5050, dtype: float64

In [4]:
atributo = pd.read_pickle("PROGRAMACAO/teste/atributo.pkl")
atributo.head(3)

      id_anuncio              id              name       value_name
0  MLB1620161340           BRAND             Marca  NICE - PECCININ
1  MLB1620161340  ITEM_CONDITION  Condição do item             Novo
2  MLB1620161340           MODEL            Modelo            TX 3C

In [5]:
tabela_dim = pd.read_pickle("PROGRAMACAO/teste/tabela_dim.pkl")
tabela_dim.head(3)

,id,title,listing_type_id,permalink,thumbnail,category_id,tags,id_seller,shipping_free_shipping,shipping_logistic_type,address_state_id,address_state_name,address_city_name
0,MLB1620161340,Controle Remoto Para Portão Peccinin Varias Co...,gold_special,https://produto.mercadolivre.com.br/MLB-162016...,http://http2.mlstatic.com/D_672731-MLB43279464...,MLB270238,"brand_verified,good_quality_picture,good_quali...",534713792,False,fulfillment,SP,São Paulo,São Paulo
1,MLB1359721693,Controle Remoto Portão Rossi Ntx 433 Nano Atto...,gold_special,https://produto.mercadolivre.com.br/MLB-135972...,http://http2.mlstatic.com/D_700327-MLB43051389...,MLB270238,"brand_verified,good_quality_picture,good_quali...",104772242,False,fulfillment,SP,São Paulo,Sertãozinho
2,MLB730238982,Placa Motor Kxh30fs Dz4 Dz3 Dz Nano Rossi Com ...,gold_special,https://produto.mercadolivre.com.br/MLB-730238...,http://http2.mlstatic.com/D_992430-MLB43144475...,MLB270238,"brand_verified,good_quality_picture,good_quali...",104772242,True,cross_docking,SP,São Paulo,Sertãozinho

In [6]:
tratando_fatos = pd.read_pickle("PROGRAMACAO/teste/tratando_fatos.pkl")
tratando_fatos.head(3)

,id,price,available_quantity,sold_quantity,shipping_logistic_type,data
0,MLB1620161340,31.99,148,1058,fulfillment,03/04/2021
1,MLB1359721693,34.77,76,1330,fulfillment,03/04/2021
2,MLB730238982,199.24,159,1008,cross_docking,03/04/2021

In [50]:
#INPUT YOUR OWN CONNECTION STRING HERE
conn_string = 'postgresql://diego:1234@localhost/hubble'

In [51]:
#perform to_sql test and print result
db = create_engine(conn_string)
conn = db.connect()

In [52]:
start_time = time.time()
sellers.to_sql('temp_seller2', con=conn, if_exists='replace', index=False)
print("to_sql duration: {} seconds".format(time.time() - start_time))

to_sql duration: 0.13962960243225098 seconds

In [ ]:
'ENGINE': 'django.db.backends.postgresql',
'NAME': 'hubble',
'USER': 'diego',
'PASSWORD': '1234',
'HOST': 'localhost',
'PORT': '5432',

In [ ]:
engine = create_engine('postgresql+psycopg2://diego:1234@localhost/hubble')
df.to_sql('temp_table', engine, if_exists= 'append')

sql = """
    UPDATE core_vendedor AS f
    SET f.col1 = t.col1
    FROM temp_table AS t
    WHERE f.id = t.id
"""

with engine.begin() as conn:     # TRANSACTION
    conn.execute(sql)

In [ ]:
import pymysql


# Connect to the database
connection = pymysql.connect(host='localhost',
                         user='root',
                         password='12345',
                         db='book')


# create cursor
cursor=connection.cursor()